apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "mysql.fullname" . }}
  labels:
  {{- include "mysql.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
  {{- include "mysql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
    {{- include "mysql.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mysql.serviceAccountName" . }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: Inspur@123
          name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: 3306tcp3306
              containerPort: 3306
              hostPort: {{ .Values.service.hostPort }}
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data
            - mountPath: /etc/mysql
              name: config
            - mountPath: /update
              name: "update"
          resources:
      {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
      volumes:
        - hostPath:
            path: {{.Values.basepath.datapath}}/omc-mysql/data
            type: DirectoryOrCreate
          name: data
        - hostPath:
            path: {{.Values.basepath.datapath}}/omc-mysql/config
            type: DirectoryOrCreate
          name: config
        - hostPath:
            path: {{.Values.basepath.datapath}}/omc-mysql/update
            type: DirectoryOrCreate
          name: "update"
      {{- with .Values.nodeName }}
      nodeName:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
  {{- end }}
