apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Values.secrets.name }}
type: Opaque
stringData:
  config.yaml: |-
    - job_name: prom-perf-simulator
      metrics_path: /prometheus
      scrape_interval: 30s
      static_configs:
        - targets:
            - oam-network-agent.oam-system:20002
